import { defineArrayMember, defineField, defineType } from "sanity";

export const homePage = defineType({
  name: "homePage",
  title: "Ana Sayfa",
  type: "document",
  description: "Yayına bu belgeden 3310 metinleri ve örnek uygulama kartları aktarılır. Hero ve alt CTA metinleri WhiteGate'in yerel içerik kaynağında yönetilir.",
  fields: [
    defineField({
      name: "seoTitle",
      title: "SEO başlığı",
      type: "string",
      validation: (rule) => rule.max(70),
    }),
    defineField({
      name: "seoDescription",
      title: "SEO açıklaması",
      type: "text",
      rows: 3,
      validation: (rule) => rule.max(220),
    }),
    defineField({
      name: "heroLead",
      title: "Hero ilk satır",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroWords",
      title: "Hero dönüşümlü ifadeler",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.required().min(1).unique(),
    }),
    defineField({
      name: "heroTail",
      title: "Hero son satır",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroDescription",
      title: "Hero açıklaması",
      type: "text",
      rows: 4,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroButtonLabel",
      title: "Hero butonu",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "ctaTag", title: "Alt CTA etiketi", type: "string" }),
    defineField({ name: "ctaLead", title: "Alt CTA ilk satır", type: "string" }),
    defineField({
      name: "ctaWords",
      title: "Alt CTA dönüşümlü ifadeler",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.unique(),
    }),
    defineField({ name: "ctaTail", title: "Alt CTA son satır", type: "string" }),
    defineField({ name: "ctaButtonLabel", title: "Alt CTA butonu", type: "string" }),
    defineField({
      name: "nokiaPhoneMessages",
      title: "3310 ekranındaki dönüşümlü mesajlar",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
      validation: (rule) => rule.min(1).max(6).unique(),
    }),
    defineField({ name: "nokiaMobileLink", title: "3310 mobil bağlantı yazısı", type: "string" }),
    defineField({ name: "nokiaCardTitle", title: "3310 kart başlığı", type: "string" }),
    defineField({ name: "nokiaCardHint", title: "3310 kart alt yazısı", type: "string" }),
    defineField({ name: "nokiaCardAction", title: "3310 kart bağlantı yazısı", type: "string" }),
    defineField({
      name: "scenarioCards",
      title: "Örnek AI uygulamaları",
      type: "array",
      of: [defineArrayMember({
        type: "object",
        title: "Uygulama kartı",
        fields: [
          defineField({ name: "number", title: "Sıra", type: "string", validation: (rule) => rule.required() }),
          defineField({ name: "team", title: "İş alanı", type: "string", validation: (rule) => rule.required() }),
          defineField({ name: "title", title: "Başlık", type: "string", validation: (rule) => rule.required() }),
          defineField({ name: "text", title: "Açıklama", type: "text", rows: 3, validation: (rule) => rule.required() }),
          defineField({ name: "steps", title: "Kısa akış", type: "string", validation: (rule) => rule.required() }),
          defineField({ name: "href", title: "Detay sayfası", type: "string", validation: (rule) => rule.required().regex(/^\//, { name: "site içi adres" }) }),
          defineField({ name: "image", title: "Kart görseli", type: "image", options: { hotspot: true }, validation: (rule) => rule.required() }),
        ],
        preview: { select: { title: "title", subtitle: "team", media: "image" } },
      })],
      validation: (rule) => rule.max(8),
    }),
  ],
  initialValue: {
    seoTitle: "AI Dönüşümü ve AI Uygulamaları | WhiteGate",
    seoDescription:
      "WhiteGate şirketlerin AI dönüşümünü planlar; size özel AI uygulamaları ve agentlar geliştirir, ekibinizle kullanıma alır.",
    heroLead: "Şirketinizi",
    heroWords: ["ilk AI uygulaması", "AI asistanı", "iş otomasyonu"],
    heroTail: "taşıyoruz.",
    heroDescription:
      "Müşteri sorularını yanıtlayan, şirket bilgisini bulan ve ekibe işinde yardımcı olan AI uygulamaları geliştiriyoruz. Hangi uygulamayla başlayacağımızı birlikte belirliyor, ekibinizle kullanıma alıyoruz.",
    heroButtonLabel: "Uygunluk Görüşmesi",
    ctaTag: "Uygunluk Görüşmesi",
    ctaLead: "Şirketinizde AI'ın",
    ctaWords: ["ilk gerçek işini", "ilk uygulama alanını", "ekibinize ilk katkısını"],
    ctaTail: "birlikte bulalım.",
    ctaButtonLabel: "Uygunluk Görüşmesi",
    nokiaPhoneMessages: ["Rapor tamam", "Ekip haberdar", "Kontrol sende"],
    nokiaMobileLink: "Nokia 3310 fikrini keşfet ↗",
    nokiaCardTitle: "Nokia 3310 ile şirket yönetilir mi?",
    nokiaCardHint: "Şaka gibi. Sistem gerçek olabilir.",
    nokiaCardAction: "Oku",
  },
  preview: {
    prepare: () => ({ title: "Ana Sayfa" }),
  },
});
